version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo go on
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      
  post_build:
    commands:
      - echo build is okay
artifacts:
  files:
    - '**/*'
