ersion: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo go on
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      
  post_build:
    commands:
      - echo build is okay
artifacts:
  files:
    - target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
